#!/bin/bash
exec 2>> /tmp/slimbookrgbkeyboard_err.txt
exec >> /tmp/slimbookrgbkeyboard_err.txt
date >&2
printf "$0 argument: %s\n" "$@" >&2

set -x

cmd="pkexec slimbookrgbkeyboard-applyconfig-pkexec $@"

cmd2="which slimbookrgbkeyboard"

if $cmd2; then
  echo "The program exists"
    if $cmd ; then
      echo "Done!"
    else 
      echo "Failed to execute command"
    fi
else
   echo "The program doesn’t exist"

fi
